### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by MaMiFreak** [brilee/MuGo#1]
Nice project! unfortunately i encountered an error and am not sure what goes wrong.
I downloaded the master branch yesterday.
the command i use: python main.py preprocess data/*
python version 3.5 ( tested 3.4 )

somehow 0 positions are allocated as test but i can't find out why

`124966 sgfs found.
Estimated number of chunks: 6101
Allocating 0 positions as test; remainder as training
Writing test chunk
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    argh.dispatch(parser)
  File "/home/boss/anaconda3/envs/tensorflow35/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/boss/anaconda3/envs/tensorflow35/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/boss/anaconda3/envs/tensorflow35/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 45, in preprocess
    process_raw_data(*data_sets, processed_dir=processed_dir)
  File "/home/boss/Downloads/CNN-Play/MuGo-master/load_data_sets.py", line 154, in process_raw_data
    test_dataset = DataSet.from_positions_w_context(test_chunk, is_test=True)
  File "/home/boss/Downloads/CNN-Play/MuGo-master/load_data_sets.py", line 106, in from_positions_w_context
    positions, next_moves, results = zip(*positions_w_context)
ValueError: not enough values to unpack (expected 3, got 0)
`

reverted the "rewrite onehot methods for small improvement" commit, error message:
ValueError: need more than 0 values to unpack

**Comment by MaMiFreak** [comment]
seems the sgf package is quite picky with the sgf it wants to read and likes to throw some errors beside StopIteration, had to edit my sgfs in order to make sure (most) of them are accepted

next to that i suspect a little bug in load_data_sets.py ( but maybe my python knowledge is lacking)

Original code:
def take_n(n, iterator):
    result = []
    try:
        for i in range(n):
            result.append(next(iterator))
    except StopIteration:
        pass
    finally:
        return result

My code:
def take_n(n, iterator):
    result = []
    for i in range(n):
        try:
            result.append(next(iterator))

        except:         #TODO this is bad!!!!! catch only appropriate exceptions (find sgf source)
            pass
    return result
