### ISSUE TITLE
NameError: name 'find_sgf_files' is not defined

### ISSUE THREAD

**Issue by lees2004** [brilee/MuGo#13]
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    argh.dispatch(parser)
  File "C:\Users\LEO\AppData\Local\Programs\Python\Python35\lib\site-packages\ar
    for line in lines:
  File "C:\Users\LEO\AppData\Local\Programs\Python\Python35\lib\site-packages\ar
    for line in result:
  File "C:\Users\LEO\AppData\Local\Programs\Python\Python35\lib\site-packages\ar
    result = function(*positional, **keywords)
  File "main.py", line 49, in preprocess
    sgf_files = list(find_sgf_files(*data_sets))
NameError: name 'find_sgf_files' is not defined

**Comment by brilee** [comment]
I fixed this, can you try pulling + running again? maybe your pull didn't apply cleanly because you had edits already?
