### ISSUE TITLE
MCTS error

### ISSUE THREAD

**Issue by hwcn** [brilee/MuGo#14]
Plicy works fine.
C:\MuGo>python main.py gtp policy --read-file=model\savedmodel
GTP engine ready
genmove b        (I type)
= Q16

MCTS does not work. Error messages as below.
C:\MuGo>python main.py gtp mcts --read-file=model\savedmodel
GTP engine ready
genmove b      (I type)
tree search
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    argh.dispatch(parser)
  File "c:\python35\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "c:\python35\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "c:\python35\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 40, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "c:\python35\lib\site-packages\pygtp-0.2-py3.5.egg\gtp.py", line 154, in send
  File "c:\python35\lib\site-packages\pygtp-0.2-py3.5.egg\gtp.py", line 222, in cmd_genmove
  File "C:\MuGo\strategies.py", line 81, in get_move
    move = self.suggest_move(self.position)
  File "C:\MuGo\strategies.py", line 236, in suggest_move
    self.tree_search(root)
  File "C:\MuGo\strategies.py", line 246, in tree_search
    position = chosen_leaf.compute_position()
  File "C:\MuGo\strategies.py", line 183, in compute_position
    self.position = self.parent.position.play_move(self.move)
TypeError: play_move() missing 1 required positional argument: 'c'

**Comment by jayjinseokkim** [comment]
exactly same error on MCTS here. Anybody can help??

**Comment by brilee** [comment]
Should be fixed.
