### ISSUE TITLE
NameError: name 'protocol_version' is not defined

### ISSUE THREAD

**Issue by XinyuFeng** [brilee/MuGo#19]
I run this program by using:
gogui-twogtp -black 'python main.py gtp policy --read-file=/tmp/savedmodel' -white 'gogui-display' -size 19 -komi 7.5 -verbose -auto

My machine meets all those requirements (gtp....);
and the Error goes here:
GTP engine ready
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    argh.dispatch(parser)
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python2.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 31, in gtp
    inpt = input()
  File "<string>", line 1, in <module>
NameError: name 'protocol_version' is not defined
B>> name
B>> version
B>> list_commands
The Go program terminated unexpectedly.

**Comment by brilee** [comment]
You're using python2, not python3. Python3's `input` function is the equivalent of Python2's `raw_input`. That line `inpt = input()` was meant to receive a string, but instead attempted to assign `inpt = exec(raw_input())`, leading to the error you see.

The issue can be fixed in one of two ways: 1) use python3 2) fix the pygtp library to be both python2 and 3 compatible. I'd recommend #1.
