### ISSUE TITLE
AttributeError: 'PolicyNetwork' object has no attribute 'output'

### ISSUE THREAD

**Issue by MartinDevelopment** [brilee/MuGo#22]
Hello, I am getting this error while trying to generate a move.
```
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    argh.dispatch(parser)
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 51, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 81, in get_move
    move = self.suggest_move(self.position)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 233, in suggest_move
    move_probs = self.policy_network.run(position)
  File "/home/mrmartinke/Desktop/MuGo-master/policy.py", line 152, in run
    probabilities = self.session.run(self.output, feed_dict={self.x: processed_position[None, :]})[0]
AttributeError: 'PolicyNetwork' object has no attribute 'output'
```

**Comment by brilee** [comment]
should be fixed, thanks for report.
