### ISSUE TITLE
NameError: name 'copy' is not defined

### ISSUE THREAD

**Issue by MartinDevelopment** [brilee/MuGo#23]
Hello, I am getting an error while trying to run mcts.

```
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T   
19 . . . . . . . . . . . . . . . . . . . 19 
18 . . . . . . . . . . . . . . . . . . . 18 
17 . . . . . . . . . . . . . . . . . . . 17 
16 . . . . . . . . . . . . . . . X O<. . 16 
15 . . . . . . . . . . . . . . . . . . . 15 
14 . . . . . . . . . . . . . . . . . . . 14 
13 . . . . . . . . . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . . . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . . . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . . . . . . . . . . . . . . . . . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 2. Captures X: 0 O: 0

Traceback (most recent call last):
  File "main.py", line 109, in <module>
    argh.dispatch(parser)
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 51, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 81, in get_move
    move = self.suggest_move(self.position)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 236, in suggest_move
    self.tree_search(root)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 256, in tree_search
    value = self.estimate_value(root, chosen_leaf)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 265, in estimate_value
    current = copy.deepcopy(leaf_position)
NameError: name 'copy' is not defined
```

**Comment by xhw98** [comment]
i also get wrong like this, could anyone help me to fix?

**Comment by Cbuenobust7** [comment]
import copy
