### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 'root'

### ISSUE THREAD

**Issue by MartinDevelopment** [brilee/MuGo#24]
```
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T   
19 . . . . . . . . . . . . . . . . . . . 19 
18 . . . . . . . . . . . . . . . . . . . 18 
17 . . . . . . . . . . . . . . . . . . . 17 
16 . . . . . . . . . . . . . . . O<. . . 16 
15 . . . . . . . . . . . . . . . . . . . 15 
14 . . . . . . . . . . . . . . . . . . . 14 
13 . . . . . . . . . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . . . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . X . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . . . . . . . . . . . . . . . . . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 2. Captures X: 0 O: 0

max rollout depth exceeded!
value: -54.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T   
19 . . . . . . . . . . . . . . . . . . . 19 
18 . . . . . . . . . . . . . . . . . . . 18 
17 . . . . . . . . . . . . . . . . . . . 17 
16 . . . . . . . . . . . . . . . . O<. . 16 
15 . . . . . . . . . . . . . . . . . . . 15 
14 . . . . . . . . . . . . . . . . . . . 14 
13 . . . . . . . . . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . . . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . X . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . . . . . . . . . . . . . . . . . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 2. Captures X: 0 O: 0

max rollout depth exceeded!
value: 33.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T   
19 . . . . . . . . . . . . . . . . . . . 19 
18 . . . . . . . . . . . . . . . . . . . 18 
17 . . . . . . . . . . . . . . . . . . . 17 
16 . . . . . . . . . . . . . . . . O . . 16 
15 . . . . . . . . . . . . . . . . . . . 15 
14 . . . . . . . . . . . . . . . . . . . 14 
13 . . . . . . . . . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . . . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . X . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . . X<. . . . . . . . . . . . . . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 3. Captures X: 0 O: 0

max rollout depth exceeded!
value: -33.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T   
19 . . . . . . . . . . . . . . . . . . . 19 
18 . . . . . . . . . . . . . . . . . . . 18 
17 . . . . . . . . . . . . . . . . . . . 17 
16 . . . X<. . . . . . . . . . . . O . . 16 
15 . . . . . . . . . . . . . . . . . . . 15 
14 . . . . . . . . . . . . . . . . . . . 14 
13 . . . . . . . . . . . . . . . . . . . 13 
12 . . . . . . . . . . . . . . . . . . . 12 
11 . . . . . . . . . . . . . . . . . . . 11 
10 . . . . . . . . . . . . . . . . . . . 10 
 9 . . . . . . . X . . . . . . . . . . .  9 
 8 . . . . . . . . . . . . . . . . . . .  8 
 7 . . . . . . . . . . . . . . . . . . .  7 
 6 . . . . . . . . . . . . . . . . . . .  6 
 5 . . . . . . . . . . . . . . . . . . .  5 
 4 . . . . . . . . . . . . . . . . . . .  4 
 3 . . . . . . . . . . . . . . . . . . .  3 
 2 . . . . . . . . . . . . . . . . . . .  2 
 1 . . . . . . . . . . . . . . . . . . .  1 
   A B C D E F G H J K L M N O P Q R S T   
Move: 3. Captures X: 0 O: 0

value: -46.5
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    argh.dispatch(parser)
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/mrmartinke/.local/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 51, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 85, in get_move
    move = self.suggest_move(self.position)
  File "/home/mrmartinke/Desktop/MuGo-master/strategies.py", line 243, in suggest_move
    return max(root.children.keys(), key=lambda move, root: root.children[move])
TypeError: <lambda>() missing 1 required positional argument: 'root'

```

**Comment by brilee** [comment]
fixed
