### ISSUE TITLE
IllegalMove

### ISSUE THREAD

**Issue by RESBI** [brilee/MuGo#39]
When I connect the robot to CGBAN,
It often says IllegalMove
and ended the program

I think the problem is the Go Rule,
But what Rule the Mugo use (Chinese? Japanese?)?

**Comment by RESBI** [comment]
Recent:

'tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . O<. O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . O<. . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . O<. .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . O<. . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O O<. . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 O<. X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 O<. . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . O<.  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 O<O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 O<. X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . . . . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -268.5
tree search
Investigating following position:
   A B C D E F G H J K L M N O P Q R S T
19 O O O . . . O O O O X O O O X . X . X 19
18 O O O O . O . O O O X X O . X . X X . 18
17 . O O O O . O O X X X X X X X . X . X 17
16 O . O X O . O O X . X . . X . . . X . 16
15 O O O X O O O X X . X X X X . . X X O 15
14 O X X X X X X X . . . . X . X X . . X 14
13 O X O X . . . X . . X . X . X . X . X 13
12 X X O X . X . . X . . . . X X X X X . 12
11 . . O X X . . . X . X X X X . . . X . 11
10 X X X X . X . X X X . . . X O . X X . 10
 9 X . . . X . X . . . . . X . X X . X .  9
 8 . . . . . X X X X X X X X . X X X . .  8
 7 . X X . X X . X . . . . . X . . X . .  7
 6 . . X X . . X . . . . . . . . . . . .  6
 5 X X X X X X O X . . . . . . X O X . .  5
 4 . . X . X X . . X X . . . . X X X . .  4
 3 . . X X . X X X . X . X . . . . . . .  3
 2 . . X X . . X . . . X . . . O<. . . .  2
 1 . . . . X X . X X X X . . . . . . . .  1
   A B C D E F G H J K L M N O P Q R S T
Move: 300. Captures X: 104 O: 8

value: -252.5
tree search
Traceback (most recent call last):
  File "D:\Programming\Python\mugo\MuGo-master\main.py", line 109, in <module>
    argh.dispatch(parser)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "D:\Programming\Python\mugo\MuGo-master\main.py", line 51, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "D:\Programming\Python\mugo\MuGo-master\strategies.py", line 83, in get_move
    move = self.suggest_move(self.position)
  File "D:\Programming\Python\mugo\MuGo-master\strategies.py", line 238, in suggest_move
    self.tree_search(root)
  File "D:\Programming\Python\mugo\MuGo-master\strategies.py", line 248, in tree_search
    position = chosen_leaf.compute_position()
  File "D:\Programming\Python\mugo\MuGo-master\strategies.py", line 185, in compute_position
    self.position = self.parent.position.play_move(self.move)
  File "D:\Programming\Python\mugo\MuGo-master\go.py", line 354, in play_move
    raise IllegalMove
go.IllegalMove'
