### ISSUE TITLE
AttributeError: 'PolicyNetwork' object has no attribute 'output'

### ISSUE THREAD

**Issue by Rick-Sanchez-666** [brilee/MuGo#43]
3 play black D5
=3

4 genmove white
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    argh.dispatch(parser)
  File "D:\Python\lib\site-packages\argh\dispatching.py", line 174, in dispatch
    for line in lines:
  File "D:\Python\lib\site-packages\argh\dispatching.py", line 277, in _execute_command
    for line in result:
  File "D:\Python\lib\site-packages\argh\dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 51, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "D:\Python\lib\site-packages\gtp.py", line 154, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "D:\Python\lib\site-packages\gtp.py", line 222, in cmd_genmove
    move = self._game.get_move(c)
  File "D:\MuGo-master\MuGo-master\strategies.py", line 81, in get_move
    move = self.suggest_move(self.position)
  File "D:\MuGo-master\MuGo-master\strategies.py", line 115, in suggest_move
    move_probabilities = self.policy_network.run(position)
  File "D:\MuGo-master\MuGo-master\policy.py", line 152, in run
    probabilities = self.session.run(self.output, feed_dict={self.x: processed_position[None, :]})[0]
AttributeError: 'PolicyNetwork' object has no attribute 'output'

**Comment by Rick-Sanchez-666** [comment]
thanks，i know how to deal with it。

**Comment by xhw98** [comment]
> l
could you tell me how to deal with it?i meet the same problem,thank you !

**Comment by brilee** [comment]
fixed in https://github.com/brilee/MuGo/commit/8ca84b812a0e555d06da4b616b5c2d0e90c7efb4
