### ISSUE TITLE
AttributeError: module 'gtp' has no attribute 'RESIGN'

### ISSUE THREAD

**Issue by greatken999** [brilee/MuGo#9]
error info when run "gogui-twogtp -black 'python3 main.py gtp policy --read-file=./tmp/savedmodel' -white 'gogui-display' -size 19 -komi 7.5 -verbose -auto":

B>> genmove b
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    argh.dispatch(parser)
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/local/lib/python3.5/dist-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 38, in gtp
    engine_reply = gtp_engine.send(cmd)
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 151, in send
    message_id, getattr(self, "cmd_" + command)(arguments))
  File "/usr/local/lib/python3.5/dist-packages/gtp.py", line 219, in cmd_genmove
    move = self._game.get_move(c)
  File "/mnt/ken-volume/MuGo/strategies.py", line 60, in get_move
    return utils.unparse_pygtp_coords(move)
  File "/mnt/ken-volume/MuGo/utils.py", line 41, in unparse_pygtp_coords
    if c == gtp.RESIGN:
AttributeError: module 'gtp' has no attribute 'RESIGN'
B>> final_score
W>> final_score
W<< ? unknown command: final_score
W<< 
B>> quit
W>> quit
W<< = 
W<< 
Black program died

system :ubuntu 16.04

**Comment by brilee** [comment]
I had been using a forked version of the pygtp module. The changes are merged upstream but it seems like the latest version isn't in pypi.

**Comment by brilee** [comment]
see https://github.com/jtauber/gtp/pull/6

**Comment by jtauber** [comment]
pygtp 0.4 is out with this

**Comment by brilee** [comment]
Thanks @jtauber
